------------------------------------------------------------------------------
-- $Header: vcr/data/investment_engine.sql 1.8.1.3 2005/08/16 11:51:28BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.investment_engine.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @investment_engine.sql
-- This file was generated from database instance CPAD.
--   Database Time    : 28FEB2005 17:04:44
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
------------------------------------------------------------------------------
set feedback off;
prompt Populating 2 records into table vcr.investment_engine.

-- empty table:
delete from vcr.investment_engine;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.investment_engine
  (IE_ID,DESCRIPTION,ME_SOURCE,EMAIL_ADDRESS,IGNORE_ZERO_POSITIONS,ROR_CALC_DENOMINATOR)
  values
  ('MGS','Man Global Strategies','WEBMARK','mildnriskmonitoringteam@maninvestments.com','N','NOTIONAL');
insert into vcr.investment_engine
  (IE_ID,DESCRIPTION,ME_SOURCE,EMAIL_ADDRESS,IGNORE_ZERO_POSITIONS,ROR_CALC_DENOMINATOR)
  values
  ('RMF','RMF','DATAPOOL','cbruder@maninvestments.com','Y','PRIORMARKETVALUE');
insert into vcr.investment_engine
  (IE_ID,DESCRIPTION,ME_SOURCE,EMAIL_ADDRESS,IGNORE_ZERO_POSITIONS,ROR_CALC_DENOMINATOR)
  values
  ('Glenwood','Glenwood','DATAPOOL','cbruder@maninvestments.com','Y','PRIORMARKETVALUE');

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

