------------------------------------------------------------------------------
-- $Header: vcr/data/iso_currency_code.sql 1.7.1.3 2005/08/19 15:15:14BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.iso_currency_code.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @iso_currency_code.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 17AUG2005 11:42:43
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 178 records into table vcr.iso_currency_code.

-- Truncate the table:
truncate table vcr.iso_currency_code;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AED',
      'United Arab Emirates, Dirhams'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AFA',
      'Afghanistan, Afghanis'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ALL',
      'Albania, Leke'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AMD',
      'Armenia, Drams'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ANG',
      'Netherlands Antilles, Guilders (also called Florins)'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AOA',
      'Angola, Kwanza'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ARS',
      'Argentina, Pesos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AUD',
      'Australia, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AWG',
      'Aruba, Guilders (also called Florins)'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'AZM',
      'Azerbaijan, Manats'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BAM',
      'Bosnia and Herzegovina, Convertible Marka'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BBD',
      'Barbados, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BDT',
      'Bangladesh, Taka'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BEF',
      'Belgium, Francs (obsolete) '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BGN',
      'Bulgaria, Leva'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BHD',
      'Bahrain, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BIF',
      'Burundi, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BMD',
      'Bermuda, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BND',
      'Brunei Darussalam, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BOB',
      'Bolivia, Bolivianos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BRC',
      'Brazil, Cruzeiros (obsolete) '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BRL',
      'Brazil, Brazil Real'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BSD',
      'Bahamas, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BTN',
      'Bhutan, Ngultrum'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BWP',
      'Botswana, Pulas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BYR',
      'Belarus, Rubles'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'BZD',
      'Belize, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CAD',
      'Canada, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CDF',
      'Congo/Kinshasa, Congolese Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CHF',
      'Switzerland, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CLP',
      'Chile, Pesos '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CNY',
      'China, Yuan Renminbi (in China)'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'COP',
      'Columbia, Pesos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CRC',
      'Costa Rica, Colón'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CSD',
      'Serbia, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CUP',
      'Cuba, Pesos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CVE',
      'Cape Verde, Escudos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CYP',
      'Cyprus, Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'CZK',
      'Czech Republic, Koruny'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'DJF',
      'Djibouti, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'DKK',
      'Denmark, Kroner'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'DOP',
      'Dominican Republic, Pesos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'DZD',
      'Algeria, Algeria Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'EEK',
      'Estonia, Krooni'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'EGP',
      'Egypt, Pounds'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ERN',
      'Eritrea, Nakfa'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ESP',
      'Spain, Pesetas (obsolete)'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ETB',
      'Ethiopia, Birr'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'EUR',
      'Euro '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'FJD',
      'Fiji, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'FKP',
      'Falkland Islands, Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GBP',
      'Britain (United Kingdom), Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GEL',
      'Georgia, Lari'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GGP',
      'Guernsey, Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GHC',
      'Ghana, Cedis'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GIP',
      'Gibraltar, Pounds'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GMD',
      'Gambia, Dalasi'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GNF',
      'Guinea, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GTQ',
      'Guatemala, Quetzales'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'GYD',
      'Guyana, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'HKD',
      'Hong Kong, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'HNL',
      'Honduras, Lempiras'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'HRK',
      'Croatia, Kuna'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'HTG',
      'Haiti, Gourdes'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'HUF',
      'Hungary, Forints'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'IDR',
      'Indonesia, Rupiahs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ILS',
      'Israel, New Shekels'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'IMP',
      'Isle of Man, Pounds'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'INR',
      'India, Rupees'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'IQD',
      'Iraq, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'IRR',
      'Iran, Rials'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ISK',
      'Iceland, Kronur'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ITL',
      'Italy, Lire (obsolete) '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'JEP',
      'Jersey, Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'JMD',
      'Jamaica, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'JOD',
      'Jordan, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'JPY',
      'Japan, Yen '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KES',
      'Kenya, Shillings'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KGS',
      'Kyrgyzstan, Soms'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KHR',
      'Cambodia, Riels'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KMF',
      'Comoros, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KPW',
      'Korea (North), Won '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KRW',
      'Korea (South), Won '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KWD',
      'Kuwait, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KYD',
      'Cayman Islands, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'KZT',
      'Kazakstan, Tenge'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LAK',
      'Laos, Kips '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LBP',
      'Lebanon, Pounds'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LKR',
      'Sri Lanka, Rupees'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LRD',
      'Liberia, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LSL',
      'Lesotho, Maloti'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LTL',
      'Lithuania, Litai'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LVL',
      'Latvia, Lati'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'LYD',
      'Libya, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MAD',
      'Morocco, Dirhams'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MDL',
      'Moldova, Lei'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MGA',
      'Madagascar, Ariary'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MKD',
      'Macedonia, Denars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MMK',
      'Myanmar (Burma), Kyats'
      );
commit;
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MNT',
      'Mongolia, Tugriks'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MOP',
      'Macau, Patacas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MRO',
      'Mauritania, Ouguiyas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MTL',
      'Malta, Liri'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MUR',
      'Mauritius, Rupees'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MVR',
      'Maldives (Maldive Islands), Rufiyaa'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MWK',
      'Malawi, Kwachas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MXN',
      'Mexico, Pesos'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MYR',
      'Malaysia, Ringgits'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'MZM',
      'Mozambique, Meticais'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NAD',
      'Namibia, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NGN',
      'Nigeria, Nairas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NIO',
      'Nicaragua, Gold Cordobas'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NOK',
      'Norway, Krone'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NPR',
      'Nepal, Rupees'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'NZD',
      'New Zealand, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'OMR',
      'Oman, Rials'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PAB',
      'Panama, Balboa'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PEN',
      'Peru, Nuevos Soles'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PGK',
      'Papua New Guinea, Kina'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PHP',
      'Philippines, Pesos '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PKR',
      'Pakistan, Rupees '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PLN',
      'Poland, Zlotych'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'PYG',
      'Paraguay, Guarani'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'QAR',
      'Qatar, Rials '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ROL',
      'Romania, Lei'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'RON',
      'Romania, New Lei'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'RUR',
      'Russia, Rubles'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'RWF',
      'Rwanda, Rwanda Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SAR',
      'Saudi Arabia, Riyals '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SBD',
      'Solomon Islands, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SCR',
      'Seychelles, Rupees '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SDD',
      'Sudan, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SEK',
      'Sweden, Kronor'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SGD',
      'Singapore, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SHP',
      'Saint Helena, Pounds '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SIT',
      'Slovenia, Tolars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SKK',
      'Slovakia, Koruny'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SLL',
      'Sierra Leone, Leones'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SOS',
      'Somalia, Shillings'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SPL',
      'Seborga, Luigini'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SRD',
      'Suriname, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'STD',
      'Sco Tome and Principe, Dobras'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SVC',
      'El Salvador, Colón '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SYP',
      'Syria, Pounds'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'SZL',
      'Swaziland, Emalangeni'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'THB',
      'Thailand, Baht '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TJS',
      'Tajikistan, Somoni'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TMM',
      'Turkmenistan, Manats'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TND',
      'Tunisia, Dinars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TOP',
      'Tonga, Pa''anga'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TRL',
      'Turkey, Liras'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TTD',
      'Trinidad and Tobago, Dollars '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TVD',
      'Tuvalu, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TWD',
      'Taiwan New, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'TZS',
      'Tanzania, Shillings'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'UAH',
      'Ukraine, Hryvnia'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'UGX',
      'Uganda, Shillings'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'USD',
      'United States of America, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'UYU',
      'Uruguay, Pesos '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'UZS',
      'Uzbekistan, Sums'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'VEB',
      'Venezuela, Bolivares'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'VND',
      'Vietnam, Dong'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'VUV',
      'Vanuatu, Vatu'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'WST',
      'Samoa, Tala'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XAF',
      'Communauti Financihre Africaine BEAC, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XAG',
      'Silver, Ounces'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XAU',
      'Gold, Ounces'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XCD',
      'East Caribbean, Dollars'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XDR',
      'International Monetary Fund (IMF) Special Drawing Rights'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XOF',
      'Communauti Financihre Africaine BCEAO, Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XPD',
      'Palladium Ounces'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XPF',
      'Comptoirs Frangais du Pacifique Francs'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XPT',
      'Platinum, Ounces'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'XXX',
      'http://www.xe.com/iso4217.htm'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'YER',
      'Yemen, Rials '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ZAR',
      'South Africa, Rand '
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ZMK',
      'Zambia, Kwacha'
      );
insert into vcr.iso_currency_code
      (ISO_CURRENCY_CODE,DESCRIPTION)
values(
      'ZWD',
      'Zimbabwe, Dollars'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

