------------------------------------------------------------------------------
-- $Header: vcr/data/iso_country_code.sql 1.7.1.4 2005/08/19 15:14:05BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.iso_country_code.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @iso_country_code.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 17AUG2005 11:42:31
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 242 records into table vcr.iso_country_code.

-- Truncate the table:
truncate table vcr.iso_country_code;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ABW',
      'AW',
      'ARUBA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AFG',
      'AF',
      'AFGHANISTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AGO',
      'AO',
      'ANGOLA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AIA',
      'AI',
      'ANGUILLA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ALB',
      'AL',
      'ALBANIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AND',
      'AD',
      'ANDORRA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ANT',
      'AN',
      'NETHERLANDS ANTILLES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ARE',
      'AE',
      'UNITED ARAB EMIRATES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ARG',
      'AR',
      'ARGENTINA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ARM',
      'AM',
      'ARMENIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ASM',
      'AS',
      'AMERICAN SAMOA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ATA',
      'AQ',
      'ANTARCTICA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ATF',
      'TF',
      'FRENCH SOUTHERN TERRITORIES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ATG',
      'AG',
      'ANTIGUA AND BARBUDA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AUS',
      'AU',
      'AUSTRALIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AUT',
      'AT',
      'AUSTRIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'AZE',
      'AZ',
      'AZERBAIJAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BDI',
      'BI',
      'BURUNDI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BEL',
      'BE',
      'BELGIUM'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BEN',
      'BJ',
      'BENIN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BFA',
      'BF',
      'BURKINA FASO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BGD',
      'BD',
      'BANGLADESH'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BGR',
      'BG',
      'BULGARIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BHR',
      'BH',
      'BAHRAIN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BHS',
      'BS',
      'BAHAMAS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BIH',
      'BA',
      'BOSNIA AND HERZEGOWINA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BLR',
      'BY',
      'BELARUS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BLZ',
      'BZ',
      'BELIZE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BMU',
      'BM',
      'BERMUDA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BOL',
      'BO',
      'BOLIVIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BRA',
      'BR',
      'BRAZIL'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BRB',
      'BB',
      'BARBADOS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BRN',
      'BN',
      'BRUNEI DARUSSALAM'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BTN',
      'BT',
      'BHUTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BVT',
      'BV',
      'BOUVET ISLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'BWA',
      'BW',
      'BOTSWANA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CAF',
      'CF',
      'CENTRAL AFRICAN REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CAN',
      'CA',
      'CANADA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CCK',
      'CC',
      'COCOS (KEELING) ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CHE',
      'CH',
      'SWITZERLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CHL',
      'CL',
      'CHILE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CHN',
      'CN',
      'CHINA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CIV',
      'CI',
      'COTE D''IVOIRE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CMR',
      'CM',
      'CAMEROON'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'COD',
      'CD',
      'CONGO, THE SO-CALLED DEMOCRATIC REPUBLIC OF THE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'COG',
      'CG',
      'CONGO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'COK',
      'CK',
      'COOK ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'COL',
      'CO',
      'COLOMBIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'COM',
      'KM',
      'COMOROS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CPV',
      'CV',
      'CAPE VERDE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CRI',
      'CR',
      'COSTA RICA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CUB',
      'CU',
      'CUBA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CXR',
      'CX',
      'CHRISTMAS ISLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CYM',
      'KY',
      'CAYMAN ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CYP',
      'CY',
      'CYPRUS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'CZE',
      'CZ',
      'CZECH REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DEU',
      'DE',
      'GERMANY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DJI',
      'DJ',
      'DJIBOUTI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DMA',
      'DM',
      'DOMINICA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DNK',
      'DK',
      'DENMARK'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DOM',
      'DO',
      'DOMINICAN REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'DZA',
      'DZ',
      'ALGERIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ECU',
      'EC',
      'ECUADOR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'EGY',
      'EG',
      'EGYPT'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ERI',
      'ER',
      'ERITREA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ESH',
      'EH',
      'WESTERN SAHARA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ESP',
      'ES',
      'SPAIN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'EST',
      'EE',
      'ESTONIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ETH',
      'ET',
      'ETHIOPIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'EU',
      'EU',
      'EUROPEAN UNION'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FIN',
      'FI',
      'FINLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FJI',
      'FJ',
      'FIJI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FLK',
      'FK',
      'FALKLAND ISLANDS (MALVINAS)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FRA',
      'FR',
      'FRANCE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FRO',
      'FO',
      'FAROE ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FSM',
      'FM',
      'MICRONESIA, FEDERATED STATES OF'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'FXX',
      'FX',
      'FRANCE, METROPOLITAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GAB',
      'GA',
      'GABON'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GBR',
      'GB',
      'UNITED KINGDOM'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GEO',
      'GE',
      'GEORGIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GG',
      'GG',
      'GUERNSEY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GHA',
      'GH',
      'GHANA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GIB',
      'GI',
      'GIBRALTAR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GIN',
      'GN',
      'GUINEA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GLP',
      'GP',
      'GUADELOUPE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GMB',
      'GM',
      'GAMBIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GNB',
      'GW',
      'GUINEA-BISSAU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GNQ',
      'GQ',
      'EQUATORIAL GUINEA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GRC',
      'GR',
      'GREECE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GRD',
      'GD',
      'GRENADA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GRL',
      'GL',
      'GREENLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GTM',
      'GT',
      'GUATEMALA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GUF',
      'GF',
      'FRENCH GUIANA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GUM',
      'GU',
      'GUAM'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'GUY',
      'GY',
      'GUYANA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HKG',
      'HK',
      'HONG KONG'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HMD',
      'HM',
      'HEARD AND MC DONALD ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HND',
      'HN',
      'HONDURAS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HRV',
      'HR',
      'CROATIA'
      );
commit;
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HTI',
      'HT',
      'HAITI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'HUN',
      'HU',
      'HUNGARY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IDN',
      'ID',
      'INDONESIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IND',
      'IN',
      'INDIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IOT',
      'IO',
      'BRITISH INDIAN OCEAN TERRITORY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IRL',
      'IE',
      'IRELAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IRN',
      'IR',
      'IRAN (ISLAMIC REPUBLIC OF)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'IRQ',
      'IQ',
      'IRAQ'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ISL',
      'IS',
      'ICELAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ISR',
      'IL',
      'ISRAEL'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ITA',
      'IT',
      'ITALY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'JAM',
      'JM',
      'JAMAICA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'JE',
      'JE',
      'JERSEY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'JOR',
      'JO',
      'JORDAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'JPN',
      'JP',
      'JAPAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KAZ',
      'KZ',
      'KAZAKHSTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KEN',
      'KE',
      'KENYA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KGZ',
      'KG',
      'KYRGYZSTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KHM',
      'KH',
      'CAMBODIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KIR',
      'KI',
      'KIRIBATI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KNA',
      'KN',
      'SAINT KITTS AND NEVIS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KOR',
      'KR',
      'KOREA, REPUBLIC OF'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'KWT',
      'KW',
      'KUWAIT'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LAO',
      'LA',
      'LAO PEOPLE''S DEMOCRATIC REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LBN',
      'LB',
      'LEBANON'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LBR',
      'LR',
      'LIBERIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LBY',
      'LY',
      'LIBYAN ARAB JAMAHIRIYA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LCA',
      'LC',
      'SAINT LUCIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LIE',
      'LI',
      'LIECHTENSTEIN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LKA',
      'LK',
      'SRI LANKA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LSO',
      'LS',
      'LESOTHO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LTU',
      'LT',
      'LITHUANIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LUX',
      'LU',
      'LUXEMBOURG'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'LVA',
      'LV',
      'LATVIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MAC',
      'MO',
      'MACAU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MAR',
      'MA',
      'MOROCCO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MCO',
      'MC',
      'MONACO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MDA',
      'MD',
      'MOLDOVA, REPUBLIC OF'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MDG',
      'MG',
      'MADAGASCAR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MDV',
      'MV',
      'MALDIVES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MEX',
      'MX',
      'MEXICO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MHL',
      'MH',
      'MARSHALL ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MKD',
      'MK',
      'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MLI',
      'ML',
      'MALI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MLT',
      'MT',
      'MALTA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MMR',
      'MM',
      'MYANMAR (Burma)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MNG',
      'MN',
      'MONGOLIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MNP',
      'MP',
      'NORTHERN MARIANA ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MOZ',
      'MZ',
      'MOZAMBIQUE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MRT',
      'MR',
      'MAURITANIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MSR',
      'MS',
      'MONTSERRAT'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MTQ',
      'MQ',
      'MARTINIQUE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MUS',
      'MU',
      'MAURITIUS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MWI',
      'MW',
      'MALAWI'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MYS',
      'MY',
      'MALAYSIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'MYT',
      'YT',
      'MAYOTTE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NAM',
      'NA',
      'NAMIBIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NCL',
      'NC',
      'NEW CALEDONIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NER',
      'NE',
      'NIGER'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NFK',
      'NF',
      'NORFOLK ISLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NGA',
      'NG',
      'NIGERIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NIC',
      'NI',
      'NICARAGUA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NIU',
      'NU',
      'NIUE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NLD',
      'NL',
      'NETHERLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NOR',
      'NO',
      'NORWAY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NPL',
      'NP',
      'NEPAL'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NRU',
      'NR',
      'NAURU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'NZL',
      'NZ',
      'NEW ZEALAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'OMN',
      'OM',
      'OMAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PAK',
      'PK',
      'PAKISTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PAN',
      'PA',
      'PANAMA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PCN',
      'PN',
      'PITCAIRN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PER',
      'PE',
      'PERU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PHL',
      'PH',
      'PHILIPPINES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PLW',
      'PW',
      'PALAU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PNG',
      'PG',
      'PAPUA NEW GUINEA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'POL',
      'PL',
      'POLAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PRI',
      'PR',
      'PUERTO RICO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PRK',
      'KP',
      'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PRT',
      'PT',
      'PORTUGAL'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PRY',
      'PY',
      'PARAGUAY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'PYF',
      'PF',
      'FRENCH POLYNESIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'QAT',
      'QA',
      'QATAR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'REU',
      'RE',
      'REUNION'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ROM',
      'RO',
      'ROMANIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'RUS',
      'RU',
      'RUSSIAN FEDERATION'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'RWA',
      'RW',
      'RWANDA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SAU',
      'SA',
      'SAUDI ARABIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SDN',
      'SD',
      'SUDAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SEN',
      'SN',
      'SENEGAL'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SGP',
      'SG',
      'SINGAPORE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SGS',
      'GS',
      'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SHN',
      'SH',
      'ST. HELENA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SJM',
      'SJ',
      'SVALBARD AND JAN MAYEN ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SLB',
      'SB',
      'SOLOMON ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SLE',
      'SL',
      'SIERRA LEONE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SLV',
      'SV',
      'EL SALVADOR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SMR',
      'SM',
      'SAN MARINO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SOM',
      'SO',
      'SOMALIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SPM',
      'PM',
      'ST. PIERRE AND MIQUELON'
      );
commit;
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'STP',
      'ST',
      'SAO TOME AND PRINCIPE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SUR',
      'SR',
      'SURINAME'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SVK',
      'SK',
      'SLOVAK REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SVN',
      'SI',
      'SLOVENIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SWE',
      'SE',
      'SWEDEN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SWZ',
      'SZ',
      'SWAZILAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SYC',
      'SC',
      'SEYCHELLES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'SYR',
      'SY',
      'SYRIAN ARAB REPUBLIC'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TCA',
      'TC',
      'TURKS AND CAICOS ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TCD',
      'TD',
      'CHAD'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TGO',
      'TG',
      'TOGO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'THA',
      'TH',
      'THAILAND'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TJK',
      'TJ',
      'TAJIKISTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TKL',
      'TK',
      'TOKELAU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TKM',
      'TM',
      'TURKMENISTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TMP',
      'TP',
      'EAST TIMOR'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TON',
      'TO',
      'TONGA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TTO',
      'TT',
      'TRINIDAD AND TOBAGO'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TUN',
      'TN',
      'TUNISIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TUR',
      'TR',
      'TURKEY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TUV',
      'TV',
      'TUVALU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TWN',
      'TW',
      'TAIWAN, PROVINCE OF CHINA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'TZA',
      'TZ',
      'TANZANIA, UNITED REPUBLIC OF'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'UGA',
      'UG',
      'UGANDA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'UKR',
      'UA',
      'UKRAINE'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'UMI',
      'UM',
      'UNITED STATES MINOR OUTLYING ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'URY',
      'UY',
      'URUGUAY'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'USA',
      'US',
      'UNITED STATES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'UZB',
      'UZ',
      'UZBEKISTAN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VAT',
      'VA',
      'HOLY SEE (VATICAN CITY STATE)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VCT',
      'VC',
      'SAINT VINCENT AND THE GRENADINES'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VEN',
      'VE',
      'VENEZUELA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VGB',
      'VG',
      'VIRGIN ISLANDS (BRITISH)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VIR',
      'VI',
      'VIRGIN ISLANDS (U.S.)'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VNM',
      'VN',
      'VIET NAM'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'VUT',
      'VU',
      'VANUATU'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'WLF',
      'WF',
      'WALLIS AND FUTUNA ISLANDS'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'WSM',
      'WS',
      'SAMOA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'YEM',
      'YE',
      'YEMEN'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'YUG',
      'YU',
      'YUGOSLAVIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ZAF',
      'ZA',
      'SOUTH AFRICA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ZMB',
      'ZM',
      'ZAMBIA'
      );
insert into vcr.iso_country_code
      (ISO_COUNTRY_CODE3,ISO_COUNTRY_CODE2,DESCRIPTION)
values(
      'ZWE',
      'ZW',
      'ZIMBABWE'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

