------------------------------------------------------------------------------
-- $Header: vcr/data/limit_version.sql 1.3 2005/07/08 12:24:11BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.limit_version.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @limit_version.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:45
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 15 records into table vcr.limit_version.

-- Truncate the table:
delete from vcr.limit_version;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(1,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(2,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(3,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(4,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(5,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(6,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(7,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(8,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(9,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(10,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(11,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(12,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(13,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(14,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
insert into vcr.limit_version
      (LIMIT_ID,LIMIT_VERSION,START_DATE,END_DATE,CHANGE_REASON)
values(15,1,to_date('20050401000000','YYYYMMDDHH24MISS'),NULL,
      'Initial Version'
      );
--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

