------------------------------------------------------------------------------
-- $Header: vcr/data/limit.sql 1.3 2005/07/08 12:24:12BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.limit.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @limit.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:39
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 15 records into table vcr.limit.

-- Truncate the table:
delete from vcr.limit;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(1,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(4,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(5,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(6,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(7,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(8,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(9,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(10,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(11,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(12,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(13,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(14,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(15,5,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(2,6,1,
      'MGS Limit'
      );
insert into vcr.limit
      (LIMIT_ID,MEASURE_ID,RULE_ID,CHANGE_REASON)
values(3,7,1,
      'MGS Limit'
      );


--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

