------------------------------------------------------------------------------
-- $Header: vcr/data/limit_header_parameter.sql 1.2.1.4 2005/10/25 14:35:23BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.limit_header_parameter.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @limit_header_parameter.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:44
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating records into table vcr.limit_header_parameter.

alter table vcr.limit_header_value disable constraint fk_limit_header_parameter;
alter table vcr.measure_rule_limit_head_param disable constraint fk_mrlhp_header_param;
-- Truncate the table:
delete from vcr.limit_header_parameter;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.limit_header_parameter
      (PARAMETER_NAME,COLUMN_NAME,HEADER_PARAMETER_ID,GET_DESC_PROCEDURE,PARENT_COLUMN_NAME)
values(
      'Fund',
      'source_fund_id',1,
      'begin :1 := vcr.pkg_source_fund.get_description(to_number(:2));end;',
      'source_id,ie_id'
      );
insert into vcr.limit_header_parameter
      (PARAMETER_NAME,COLUMN_NAME,HEADER_PARAMETER_ID,GET_DESC_PROCEDURE,PARENT_COLUMN_NAME)
values(
      'Instrument Type',
      'ie_instrument_type_id',4,
      'begin :1 := vcr.pkg_instrument_type.get_ie_description(to_number(:2)); end;',
      'ie_id'
      );
insert into vcr.limit_header_parameter
      (PARAMETER_NAME,COLUMN_NAME,HEADER_PARAMETER_ID,GET_DESC_PROCEDURE)
values(
      'Investment Engine',
      'ie_id',2,
      'begin :1 := vcr.pkg_investment_engine.get_description(:2); end;'
      );
insert into vcr.limit_header_parameter
      (PARAMETER_NAME,COLUMN_NAME,HEADER_PARAMETER_ID,GET_DESC_PROCEDURE,PARENT_COLUMN_NAME)
values(
      'Strategy',
      'source_strategy_id',3,
      'begin :1 := vcr.pkg_source_strategy.get_description(to_number(:2); end;',
      'source_id,ie_id'
      );
insert into vcr.limit_header_parameter
      (PARAMETER_NAME,COLUMN_NAME,HEADER_PARAMETER_ID,GET_DESC_PROCEDURE)
values(
      'Source',
      'source_id',5,
      'begin :1 := vcr.pkg_source.get_source_name(to_number(:2); end;'
      );

--{{END AUTOGENERATED CODE}}

commit;

alter table vcr.limit_header_value enable constraint fk_limit_header_parameter;
alter table vcr.measure_rule_limit_head_param enable constraint fk_mrlhp_header_param;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

