------------------------------------------------------------------------------
-- $Header: vcr/data/limit_param_value.sql 1.3 2005/07/08 12:24:11BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.limit_param_value.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @limit_param_value.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:44
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 30 records into table vcr.limit_param_value.

-- Truncate the table:
delete from vcr.limit_param_value;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(1,1,1,.0252,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(1,1,2,-.0252,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(2,1,1,.005,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(2,1,2,-.005,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(3,1,1,.005,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(3,1,2,-.005,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(4,1,1,.0236,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(4,1,2,-.0236,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(5,1,1,.0315,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(5,1,2,-.0315,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(6,1,1,.0189,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(6,1,2,-.0189,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(7,1,1,.0189,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(7,1,2,-.0189,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(8,1,1,.0189,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(8,1,2,-.0189,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(9,1,1,.0394,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(9,1,2,-.0394,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(10,1,1,.0189,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(10,1,2,-.0189,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(11,1,1,.0126,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(11,1,2,-.0126,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(12,1,1,.0189,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(12,1,2,-.0189,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(13,1,1,.03,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(13,1,2,-.03,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(14,1,1,.0157,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(14,1,2,-.0157,
      'lower'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(15,1,1,.03,
      'upper'
      );
insert into vcr.limit_param_value
      (LIMIT_ID,LIMIT_VERSION,RULE_PARAMETER_ID,VALUE,CHANGE_REASON)
values(15,1,2,-.03,
      'lower'
      );
--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

