------------------------------------------------------------------------------
-- $Header: vcr/data/limit_exception_class.sql 1.2 2005/08/22 19:38:22BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.limit_exception_class.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @limit_exception_class.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 22AUG2005 19:10:53
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 4 records into table vcr.limit_exception_class.

-- Truncate the table:
truncate table vcr.limit_exception_class;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.limit_exception_class
      (CLASS,DESCRIPTION)
values(
      'LIMIT_BREAK_ERR',
      'Break against limit - error'
      );
insert into vcr.limit_exception_class
      (CLASS,DESCRIPTION)
values(
      'LIMIT_BREAK_OK',
      'Break against limit - reasonable'
      );
insert into vcr.limit_exception_class
      (CLASS,DESCRIPTION)
values(
      'VAL_ERROR_BOOKING',
      'Valuation Error - Wrong Booking'
      );
insert into vcr.limit_exception_class
      (CLASS,DESCRIPTION)
values(
      'VAL_ERROR_PRICE',
      'Valuation Error - Wrong Price'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

