------------------------------------------------------------------------------
-- $Header: vcr/data/measure_rule_limit_head_param.sql 1.3 2005/07/08 12:24:13BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.measure_rule_limit_head_param.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @measure_rule_limit_head_param.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:45
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 3 records into table vcr.measure_rule_limit_head_param.

-- Truncate the table:
delete from vcr.measure_rule_limit_head_param;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.measure_rule_limit_head_param
      (MEASURE_ID,RULE_ID,HEADER_PARAMETER_ID)
values(5,1,1
      );
insert into vcr.measure_rule_limit_head_param
      (MEASURE_ID,RULE_ID,HEADER_PARAMETER_ID)
values(6,1,2
      );
insert into vcr.measure_rule_limit_head_param
      (MEASURE_ID,RULE_ID,HEADER_PARAMETER_ID)
values(7,1,2
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

