------------------------------------------------------------------------------
-- $Header: vcr/data/measure_rule.sql 1.2.1.1 2005/05/17 13:26:01BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.measure_rule.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @measure_rule.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:45
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 3 records into table vcr.measure_rule.

-- Truncate the table:
delete from vcr.measure_rule;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.measure_rule
      (MEASURE_ID,RULE_ID)
values(5,1
      );
insert into vcr.measure_rule
      (MEASURE_ID,RULE_ID)
values(6,1
      );
insert into vcr.measure_rule
      (MEASURE_ID,RULE_ID)
values(7,1
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

