------------------------------------------------------------------------------
-- $Header: vcr/data/ref_type_map.sql 1.2.1.5 2005/08/23 18:27:18BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.ref_type_map.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @ref_type_map.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 23AUG2005 18:12:25
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 9 records into table vcr.ref_type_map.

-- Truncate the table:
truncate table vcr.ref_type_map;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'OBJECT',
      'FUNDM',
      'MEFUND'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'OBJECT',
      'FUNDF',
      'BENCHMARKFUND'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'OBJECT',
      'FUNDD',
      'BENCHMARKFUND'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'OBJECT',
      'STRATEGYM',
      'MESTRATEGY'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'MEASURE',
      'Notional',
      'NOTIONAL'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'MEASURE',
      'MTD PnL - MTD PnL / Notional',
      'MTDROR'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'MEASURE',
      'NAV / Share',
      'NAVPERSHARE'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'MEASURE',
      'MTD PnL',
      'MTDPNL'
      );
insert into vcr.ref_type_map
      (REF_SOURCE,MAP,SOURCE_TYPE,VCR_TYPE)
values(
      'WEBMARK',
      'MEASURE',
      'Daily PnL',
      'DAILYPNL'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

