------------------------------------------------------------------------------
-- $Header: vcr/data/ref_source.sql 1.5.1.4 2005/10/13 12:52:48BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.ref_source.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus vcr/[password]@[instance] @ref_source.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 13OCT2005 12:50:30
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
set scan off;
prompt Populating 2 records into table vcr.ref_source.

-- Truncate the table:
truncate table vcr.ref_source;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.ref_source
      (REF_SOURCE,REF_SOURCE_TYPE,GET_PROCEDURE)
values(
      'DATAPOOL',
      'ME_SOURCE',
      'vcr.pkg_ref_object_mod.get_datapool(:1)'
      );
insert into vcr.ref_source
      (REF_SOURCE,REF_SOURCE_TYPE,GET_PROCEDURE)
values(
      'WEBMARK',
      'ME_SOURCE',
      'vcr.pkg_ref_object_mod.get_webmark(:1)'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
set scan on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

