------------------------------------------------------------------------------
-- $Header: vcr/data/source_basis_measure_rule.sql 1.2.1.1 2005/05/17 13:26:02BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_basis_measure_rule.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_basis_measure_rule.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:46
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 6 records into table vcr.source_basis_measure_rule.

-- Truncate the table:
delete from vcr.source_basis_measure_rule;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(5,1,
      'TCLEAN'
      );
insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(6,1,
      'TCLEAN'
      );
insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(7,1,
      'TCLEAN'
      );
insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(5,1,
      'TPLUS1'
      );
insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(6,1,
      'TPLUS1'
      );
insert into vcr.source_basis_measure_rule
      (MEASURE_ID,RULE_ID,BASIS)
values(7,1,
      'TPLUS1'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

