------------------------------------------------------------------------------
-- $Header: vcr/data/source_strategy.sql 1.2 2005/04/08 10:35:02BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_strategy.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_strategy.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:48:24
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 18 records into table vcr.source_strategy.

-- empty the table:
delete from vcr.source_strategy;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Global Quant Alpha Master Fund Ltd.',
      'Quantitative Global Macro',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Jackobshorn 8B Limited',
      'Directional Global Macro',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Jackobshorn 8B Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Lucendro 5B Limited',
      'Fundamental Arbitrage',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Lucendro 5B Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Montfort 7A Limited',
      'Fundamental Arbitrage',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Montfort 7A Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Nordend 4A Limited',
      'Long/Short Equity',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Nordend 4A Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Rellerli 10A Limited',
      'Long/Short Equity',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man MAC Rellerli 10A Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Mac Rigi 4B Ltd.',
      'Dispersion',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Mac Rigi 4B Ltd.',
      'Fundamental Arbitrage',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Mac Rigi 4B Ltd.',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Mac Rigi 4B Ltd.',
      'Statistical Arbitrage',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Barnegat Fund Limited',
      'Global Macro',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Barnegat Fund Limited',
      'Non-trading P_L',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_strategy
      (SOURCE_STRATEGY_ID,FUND,STRATEGY,SOURCE_ID,ME_STRATEGY_ID,CHANGE_REASON)
values(vcr.sq_source_strategy.nextval,
      'Man Barnegat Fund Limited',
      'Relative Value',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

