------------------------------------------------------------------------------
-- $Header: vcr/data/source_instrument_type.sql 1.2 2005/04/08 10:34:54BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_instrument_type.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_instrument_type.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:48:55
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 37 records into table vcr.source_instrument_type.

-- empty the table:
delete from vcr.source_instrument_type;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'American Depository Receipt',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Basis Rate Swap',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Bond Futures',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Cash and Equivalents',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Commodity Futures',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Commodity Option',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Commodity Swap',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Common Stock',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Contract For Difference',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Currency Futures',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Currency Option',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Equity Option',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Equity Warrants',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Fixed Rate',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Forward Contract',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Fund of Funds',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Index Fund',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Index Futures',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Interest Rate Futures',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Investment Trust',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Money Market',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Mutual Fund',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Option on Future',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Preference Stock',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Preferred Stock',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Real Estate Investment Trust',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Repurchase Agreement',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Rights',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Swaptions',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Treasury Bill',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Treasury Bond',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Treasury Note',4,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Global Depository Receipt',4,
      'Created by [BOB TPLUS1 29-MAR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Bond Forward',4,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Commodities',4,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Inflation Index Swap',4,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_instrument_type
      (SOURCE_INSTRUMENT_TYPE_ID,INSTRUMENT_TYPE,SOURCE_ID,CHANGE_REASON)
values(vcr.sq_source_instrument_type.nextval,
      'Interest Rate Swap',4,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

