------------------------------------------------------------------------------
-- $Header: vcr/data/source_ie_ins_type.sql 1.2 2005/04/08 10:34:58BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_ie_ins_type.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_ie_ins_type.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:49:34
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 37 records into table vcr.source_ie_ins_type.

delete from vcr.source_ie_ins_type;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(1,2,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(1,7,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(2,30,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(2,31,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(2,32,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(2,14,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(3,3,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(3,34,
      'UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(7,4,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(8,9,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(14,24,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(14,8,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(14,33,
      'UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(14,25,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(14,1,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(15,12,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(17,13,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(18,21,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(20,15,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(21,10,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(23,11,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(27,5,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(27,35,
      'UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(27,18,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(28,23,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(29,36,
      'UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(30,6,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(33,19,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(33,37,
      'UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(34,27,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(36,29,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,26,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,28,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,16,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,22,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,20,
      'Initial UAT Mapping'
      );
insert into vcr.source_ie_ins_type
      (IE_INSTRUMENT_TYPE_ID,SOURCE_INSTRUMENT_TYPE_ID,CHANGE_REASON)
values(37,17,
      'Initial UAT Mapping'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

