------------------------------------------------------------------------------
-- $Header: vcr/data/source_broker.sql 1.2 2005/04/08 10:35:00BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_broker.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_broker.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:48:41
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 26 records into table vcr.source_broker.

-- empty the table:
delete from vcr.source_broker;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Bank of Butterfield International (Cayman) Ltd. - Trading',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Bear Stearns - New York FX Account',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Bear Stearns - New York Trading',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Bear Stearns - New York Trading 1',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Goldman Sachs Futures',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Goldman Sachs International CFD',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Goldman Sachs International Trading Activity',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Goldman Sachs London Trading',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Goldman Sachs Trading',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Man Financial USA - Trading',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Morgan Stanley International Futures',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Morgan Stanley International Trading Activity',4,NULL,
      'Created by [BOB TPLUS1 07-MAR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Barclays Capital Inc. - Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Barclays Capital London - Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'CITIBANK N.A. - Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Credit Suisse First Boston Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Deutsche Bank AG - London Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Gensec Bank Limited Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Gensec PN',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'JP Morgan Securities Inc - Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Mazerolles Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Merrill Lynch _ Co Inc',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Royal Bank of Canada Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Royal Bank of Scotland Plc Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'UBS AG Head Office - Trading',4,NULL,
      'Created by [BOB TPLUS1 01-APR-2005 #1]'
      );
insert into vcr.source_broker
      (SOURCE_BROKER_ID,BROKER,SOURCE_ID,PRIME_BROKER_ID,CHANGE_REASON)
values(vcr.sq_source_broker.nextval,
      'Barclays Capital London - Special Situation Investment',4,NULL,
      'Created by [BOB TCLEAN 28-FEB-2005 #2]'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

