------------------------------------------------------------------------------
-- $Header: vcr/data/source.sql 1.6.1.1 2005/03/17 14:31:47GMT apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source.sql
-- This file was generated from database instance CPAD.
--   Database Time    : 28FEB2005 17:04:46
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
------------------------------------------------------------------------------
set feedback off;
prompt Populating 6 records into table vcr.source.

-- empty table:
delete from vcr.source;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (1,'GFS',NULL,NULL,NULL,NULL);
insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (2,'IFS',NULL,NULL,NULL,NULL);
insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (3,'TYK',NULL,NULL,NULL,NULL);
insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (4,'BOB',NULL,NULL,NULL,NULL);
insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (5,'SS',NULL,NULL,NULL,NULL);
insert into vcr.source
  (SOURCE_ID,SOURCE_NAME,EMAIL_ADDRESS,SECURE_MESSAGE_ID,TCLEAN_DELAY,ROLLBACK_SEGMENT)
  values
  (6,'SSC',NULL,NULL,NULL,NULL);
--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

