------------------------------------------------------------------------------
-- $Header: vcr/data/source_basis.sql 1.5 2005/03/07 10:42:36GMT apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_basis.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_basis.sql
-- This file was generated from database instance CPAD.
--   Database Time    : 28FEB2005 17:04:47
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
------------------------------------------------------------------------------
set feedback off;
prompt Populating 2 records into table vcr.source_basis.

-- empty table:
delete from vcr.source_basis;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_basis
  (BASIS,DESCRIPTION)
  values
  ('TPLUS1','T plus 1');
insert into vcr.source_basis
  (BASIS,DESCRIPTION)
  values
  ('TCLEAN','T clean');

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

