------------------------------------------------------------------------------
-- $Header: vcr/data/source_currency.sql 1.2 2005/04/08 10:34:52BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_currency.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_currency.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:49:06
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 22 records into table vcr.source_currency.

-- empty the table:
delete from vcr.source_currency;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'AUD',4,
      'AUD',
      'Test Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'CAD',4,
      'CAD',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'CHF',4,
      'CHF',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'CNY',4,
      'CNY',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'DKK',4,
      'DKK',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'EUR',4,
      'EUR',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'GBP',4,
      'GBP',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'HKD',4,
      'HKD',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'HUF',4,
      'HUF',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'IDR',4,
      'IDR',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'INR',4,
      'INR',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'JPY',4,
      'JPY',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'KRW',4,
      'KRW',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'MYR',4,
      'MYR',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'NOK',4,
      'NOK',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'NZD',4,
      'NZD',
      'UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'PHP',4,
      'PHP',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'SEK',4,
      'SEK',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'SGD',4,
      'SGD',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'THB',4,
      'THB',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'TWD',4,
      'TWD',
      'Initial UAT Mapping'
      );
insert into vcr.source_currency
      (CURRENCY,SOURCE_ID,ISO_CURRENCY_CODE,CHANGE_REASON)
values(
      'USD',4,
      'USD',
      'Initial UAT Mapping'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

