------------------------------------------------------------------------------
-- $Header: vcr/data/source_country.sql 1.2 2005/04/08 10:34:50BST apenney PRODUCTION  $
------------------------------------------------------------------------------
-- Data population script for table vcr.source_country.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @source_country.sql
-- This file was generated from database instance VCRU1.
--   Database Time    : 07APR2005 10:49:23
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 39 records into table vcr.source_country.

-- empty the table:
delete from vcr.source_country;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Australia',4,
      'AUS',
      'Back to original value'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Austria',4,
      'AUT',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Bahamas',4,
      'BHS',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Belgium',4,
      'BEL',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Bermuda',4,
      'BMU',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Canada',4,
      'CAN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Cayman Islands',4,
      'CYM',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'China  Peoples''  Republic of',4,
      'CHN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Denmark',4,
      'DNK',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'European Union',4,NULL,
      'Test Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Finland',4,
      'FIN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'France',4,
      'FRA',
      'Intial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Germany',4,
      'DEU',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Greece',4,
      'GRC',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Hong Kong',4,
      'HKG',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Hungary',4,
      'HUN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'India',4,
      'IND',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Indonesia',4,
      'IDN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Ireland',4,
      'IRL',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Italy',4,
      'ITA',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Japan',4,
      'JPN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Korea  Republic of (South Korea)',4,
      'KOR',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Liberia',4,
      'LBR',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Luxembourg',4,
      'LUX',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Malaysia',4,
      'MYS',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Netherlands',4,
      'NLD',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'New Zealand',4,
      'NZL',
      'UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Norway',4,
      'NOR',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Panama',4,
      'PAN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Philippines',4,
      'PHL',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Portugal',4,
      'PRT',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Singapore',4,
      'SGP',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Spain',4,
      'ESP',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Sweden',4,
      'SWE',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Switzerland',4,
      'CHE',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Taiwan',4,
      'TWN',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'Thailand',4,
      'THA',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'United Kingdom',4,
      'GBR',
      'Initial UAT Mapping'
      );
insert into vcr.source_country
      (COUNTRY,SOURCE_ID,ISO_COUNTRY_CODE,CHANGE_REASON)
values(
      'United States of America',4,
      'USA',
      'Initial UAT Mapping'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

