------------------------------------------------------------------------------
-- $Header: vcr/data/target_table.sql 1.4.1.4 2005/08/22 19:38:22BST ghoekstra DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.target_table.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @target_table.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 22AUG2005 19:12:00
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 1 records into table vcr.target_table.

-- Truncate the table:
truncate table vcr.target_table;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.target_table
      (TABLE_NAME,PURGE_PROCEDURE,CHECK_PROCEDURE,CALCULATION_PROCEDURE,MONTHS_RETAINED,DISCARD_PROCEDURE,DESCRIPTION)
values(
      'source_position',
      'vcr.pkg_purger.purge_positions',
      'vcr.pkg_checker.check_positions',
      'vcr.pkg_calculator.calculate_mtd_ror',12,
      'vcr.pkg_filter.filter_positions',
      'Profilt and Loss'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

