------------------------------------------------------------------------------
-- $Header: vcr/data/target_table_dimension.sql 1.2.1.2 2005/07/21 14:20:07BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.target_table_dimension.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @target_table_dimension.sql
-- This file was generated from database instance CPAD.
--   Database Time    : 28FEB2005 17:04:49
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
------------------------------------------------------------------------------
set feedback off;
prompt Populating 6 records into table vcr.target_table_dimension.

-- empty table:
delete from vcr.target_table_dimension;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_brokers');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_countries');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_currencies');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_funds');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_instrument_types');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_strategies');
insert into vcr.target_table_dimension
  (TABLE_NAME,DIM_BUILD_PROCEDURE)
  values
  ('source_position','vcr.pkg_dim_creater.create_markets');
--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

