------------------------------------------------------------------------------
-- $Header: vcr/data/target_column.sql 1.9 2005/10/21 10:04:52BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.target_column.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @target_column.sql
-- This file was generated from database instance CPAD.
--   Database Time    : 28FEB2005 17:04:48
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
------------------------------------------------------------------------------
set feedback off;
prompt Populating vcr.target_column.

alter table vcr.field_target_column disable constraint fk_ftc_target_column;
alter table vcr.ie_target_column disable constraint fk_ie_target_column;
alter table vcr.source_mandatory_override disable constraint fk_mandatory_override_column;
-- empty table:
delete from vcr.target_column;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','fund','Fund');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','tax_lot_id','Tax Lot Id');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','sub_strategy','Sub-strategy');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','strategy','Strategy');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','transaction_id','Transaction Id');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_pnl_daily','Total Daily PNL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_pnl_mtd','Total MTD PNL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_pnl_ytd','Total YTD PNL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','option_multiplyer','OPTION_MULTIPLYER');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','first_call_or_put_date','FIRST_CALL_OR_PUT_DATE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','counterparty','COUNTERPARTY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','basis_swap_index_pay','BASIS_SWAP_INDEX_PAY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','basis_swap_index_receive','BASIS_SWAP_INDEX_RECEIVE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','bid_floating_rate_swap','BID_FLOATING_RATE_SWAP');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','ask_floating_rate_swap','ASK_FLOATING_RATE_SWAP');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','future_contract_value','FUTURE_CONTRACT_VALUE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_holding','INSTRUMENT_HOLDING');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_price_local','INSTRUMENT_PRICE_LOCAL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_unit_cost_local','INSTRUMENT_UNIT_COST_LOCAL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_price','INSTRUMENT_PRICE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_value','INSTRUMENT_VALUE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','book_coupon','Book Coupon');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','beg_book_acc_interest','Beginning Accrued Interest');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','book_unrealised_income','Book unrealised income');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_income_daily','TOTAL_INCOME_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_income_mtd','TOTAL_INCOME_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_income_ytd','TOTAL_INCOME_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_dividends_daily','UNREALISED_DIVIDENDS_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_dividends_mtd','UNREALISED_DIVIDENDS_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_dividends_ytd','UNREALISED_DIVIDENDS_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_acc_interest_daily','UNREALISED_ACC_INTEREST_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_acc_interest_mtd','UNREALISED_ACC_INTEREST_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_acc_interest_ytd','UNREALISED_ACC_INTEREST_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_dividends_daily','REALISED_DIVIDENDS_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_dividends_mtd','REALISED_DIVIDENDS_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_dividends_ytd','REALISED_DIVIDENDS_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_acc_interest_daily','REALISED_ACC_INTEREST_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_acc_interest_mtd','REALISED_ACC_INTEREST_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_acc_interest_ytd','REALISED_ACC_INTEREST_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_mtm_daily','TOTAL_MTM_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_mtm_mtd','TOTAL_MTM_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_mtm_ytd','TOTAL_MTM_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_fx_daily','TOTAL_FX_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_fx_mtd','TOTAL_FX_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_fx_ytd','TOTAL_FX_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_misc_rev_exp_daily','TOTAL_MISC_REV_EXP_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_misc_rev_exp_mtd','TOTAL_MISC_REV_EXP_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','total_misc_rev_exp_ytd','TOTAL_MISC_REV_EXP_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_mtm_daily','REALISED_MTM_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_mtm_mtd','REALISED_MTM_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_mtm_ytd','REALISED_MTM_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_fx_daily','REALISED_FX_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_fx_mtd','REALISED_FX_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','realised_fx_ytd','REALISED_FX_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_mtm_daily','UNREALISED_MTM_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_mtm_mtd','UNREALISED_MTM_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_mtm_ytd','UNREALISED_MTM_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_fx_daily','UNREALISED_FX_DAILY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_fx_mtd','UNREALISED_FX_MTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','unrealised_fx_ytd','UNREALISED_FX_YTD');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','local_market_value','LOCAL_MARKET_VALUE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','date_of_price','DATE_OF_PRICE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','bb_date_of_price','BB_DATE_OF_PRICE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','bid','BID');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','ask','ASK');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','last','LAST');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','shares_outstanding','SHARES_OUTSTANDING');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','market_capitalisation','MARKET_CAPITALISATION');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','volume','VOLUME');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','bid_size','BID_SIZE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','ask_size','ASK_SIZE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','daily_trades','DAILY_TRADES');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','daily_turnovers','DAILY_TURNOVERS');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','fx_rate','FX_RATE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','nominal_amount','NOMINAL_AMOUNT');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','delta','DELTA');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','underlying_price','UNDERLYING_PRICE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','end_local_cost','End local cost');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','position_sign','POSITION_SIGN');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_type','INSTRUMENT_TYPE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument_id','INSTRUMENT_ID');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','country','COUNTRY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','currency','CURRENCY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','instrument','INSTRUMENT');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','isin','ISIN');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','cusip','CUSIP');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','sedol','SEDOL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','bloomberg_id','BLOOMBERG_ID');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','reporting_currency','REPORTING_CURRENCY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','industry_classification','INDUSTRY_CLASSIFICATION');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','industry_group','INDUSTRY_GROUP');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','industry','INDUSTRY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','sector','SECTOR');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','region','REGION');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','yield_curve_name','YIELD_CURVE_NAME');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','market_index_name','MARKET_INDEX_NAME');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','market_name','MARKET_NAME');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','yield_curve_type','YIELD_CURVE_TYPE');
commit;
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','issuer_name','ISSUER_NAME');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','rating_bloomberg','RATING_BLOOMBERG');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','rating_moody','RATING_MOODY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','rating_sp','RATING_SP');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','rating_category','RATING_CATEGORY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','asset_class','ASSET_CLASS');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','maturity_bucket','MATURITY_BUCKET');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','maturity_bucket_detail','MATURITY_BUCKET_DETAIL');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','underlying_instrument','UNDERLYING_INSTRUMENT');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','underlying_base_instrument','UNDERLYING_BASE_INSTRUMENT');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','underlying_swap_tenor','UNDERLYING_SWAP_TENOR');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','price_source','PRICE_SOURCE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','broker','BROKER');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','futures_category','FUTURES_CATEGORY');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','maturity_date','MATURITY_DATE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','strike','STRIKE');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','call_put','CALL_PUT');
insert into vcr.target_column
  (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION)
  values
  ('source_position','expiration_date','EXPIRATION_DATE');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','exposure','exposure');

INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','pos_adjusted_delta','POS_ADJUSTED_DELTA');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','delta_value_k'     ,'DELTA_VALUE_K');

INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','total_income_mtd_local','TOTAL_INCOME_MTD_LOCAL');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','yield_to_maturity'     ,'YIELD_TO_MATURITY'     );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','modified_duration'     ,'MODIFIED_DURATION'     );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','yield_to_worst'        ,'YIELD_TO_WORST'        );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','rule_144a'             ,'RULE_144A'             );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','private_placement'     ,'PRIVATE_PLACEMENT'     );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','current_yield'         ,'CURRENT_YIELD'         );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','interest_rate'         ,'INTEREST_RATE'         );
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','rating_fitch'          ,'RATING_FITCH'          );

INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','beg_book_acc_interest_mtd','beg_book_acc_interest_mtd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','book_coupon_mtd','book_coupon_mtd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','book_unrealised_income_mtd','book_unrealised_income_mtd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','end_local_cost_mtd','end_local_cost_mtd');

INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','beg_book_acc_interest_ytd','beg_book_acc_interest_ytd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','book_coupon_ytd','book_coupon_ytd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','book_unrealised_income_ytd','book_unrealised_income_ytd');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','end_local_cost_ytd','end_local_cost_ytd');

INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','accrued_interest_local_hy','accrued_interest_local_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','accrued_interest_hy','accrued_interest_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','loan_identifier_hy','loan_identifier_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','loan_effective_date_hy','loan_effective_date_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','instrument_price_change_hy','instrument_price_change_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','instrument_value_change_hy','instrument_value_change_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','paid_interest_hy','paid_interest_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','total_committed_amount_hy','total_committed_amount_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','total_funded_amount_hy','total_funded_amount_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','base_rate_hy','base_rate_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','spread_rate_hy','spread_rate_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','paid_fees_hy','paid_fees_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','accrued_instrument_fees_hy','accrued_instrument_fees_hy');
INSERT INTO vcr.target_column (TABLE_NAME,COLUMN_NAME,COLUMN_DESCRIPTION) VALUES ('source_position','instrument_cost_value_hy','instrument_cost_value_hy');

commit;

alter table vcr.field_target_column enable constraint fk_ftc_target_column;
alter table vcr.ie_target_column enable constraint fk_ie_target_column;
alter table vcr.source_mandatory_override enable constraint fk_mandatory_override_column;

set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

