------------------------------------------------------------------------------
-- $Header: vcr/data/validation_rule_parameter.sql 1.3 2005/06/14 11:10:15BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.validation_rule_parameter.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @validation_rule_parameter.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:46
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 2 records into table vcr.validation_rule_parameter.

-- Truncate the table:
delete from vcr.validation_rule_parameter;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.validation_rule_parameter
      (RULE_ID,SEQ_ID,NAME,RULE_PARAMETER_ID,OPERATOR)
values(1,2,
      'Upper Limit',1,
      '>'
      );
insert into vcr.validation_rule_parameter
      (RULE_ID,SEQ_ID,NAME,RULE_PARAMETER_ID,OPERATOR)
values(1,1,
      'Lower Limit',2,
      '<'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

