------------------------------------------------------------------------------
-- $Header: vcr/data/validation_measure.sql 1.3.1.2 2005/07/21 14:20:08BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.validation_measure.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @validation_measure.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:46
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 3 records into table vcr.validation_measure.

-- Truncate the table:
delete from vcr.validation_measure;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.validation_measure
      (MEASURE_ID,NAME,CALC_LEVEL,UNITS,FORMAT)
values(5,
      'Daily Change Fund MTD RoR (Tolerance Level)',
      NULL,'PERCENTAGE', '990.99'
      );
insert into vcr.validation_measure
      (MEASURE_ID,NAME,CALC_LEVEL,UNITS,FORMAT)
values(6,
      'Difference VSP/Manager Fund MTD RoR',
      NULL,'PERCENTAGE', '990.99'
      );
insert into vcr.validation_measure
      (MEASURE_ID,NAME,CALC_LEVEL,UNITS,FORMAT)
values(7,
      'Difference VSP/Manager Strategy MTD RoR',
      NULL,'PERCENTAGE', '990.99'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

