------------------------------------------------------------------------------
-- $Header: vcr/data/validation_rule.sql 1.2 2005/05/17 13:26:04BST apenney DEV  $
------------------------------------------------------------------------------
-- Data population script for table vcr.validation_rule.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus "vcr/[password]@[instance]" @validation_rule.sql
-- This file was generated from database instance VCRD1.
--   Database Time    : 26APR2005 09:43:46
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : vcrdev
------------------------------------------------------------------------------
set feedback off;
prompt Populating 1 records into table vcr.validation_rule.

-- Truncate the table:
delete from vcr.validation_rule;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into vcr.validation_rule
      (RULE_ID,NAME,BREAK_MESSAGE)
values(1,
      'Range Check',
      'Outside of range limits'
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

